---
- name: Install System Packages
  sudo: yes
  yum: name={{ item }} state=latest
  with_items:
    - curl
    - wget

- name: Install Extra Packages
  sudo: yes
  yum: name={{ item }} state=latest
  with_items: server.packages
  when: server.packages is defined

- name: Configure the timezone
  sudo: yes
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/{{server.zoneinfo}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  shell: localedef -f UTF-8 -i {{server.localedef}}
  sudo: yes
