---
- name: SELinuxのDisable設定
  selinux: state=disabled

- name: Install System Packages
  sudo: yes
  yum: name={{ item }} state=latest
  with_items:
    - curl
    - wget
    - unzip
    - screen 
    - vim 
    - git 
    - rsync 
    - gcc 
    - tar 
    - make 
    - nkf

- name: Install Extra Packages
  sudo: yes
  yum: name={{ item }} state=latest
  with_items: 
    - ImageMagick 
    - ImageMagick-devel 
    - cairo 
    - cairo-devel 
    - cairomm-devel 
    - libjpeg-turbo-devel 
    - pango 
    - pango-devel 
    - pangomm 
    - pangomm-devel 
    - giflib-devel 
    - ld-linux.so.2 
    - libstdc++.so.6 
    - libfontconfig.so.1

- name: Configure the timezone
  sudo: yes
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/{{server.zoneinfo}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  shell: localedef -f UTF-8 -i {{server.localedef}}
  sudo: yes
