---
#  vars_prompt:
#  - name: yum_update
#    prompt: "Do you accept updates ?"
#    private: no
#    default: Y

    - name: Yum update packages
      yum: name=* state=latest
#      when: yum_update == "Y"

    # EPEL/Remi/RPMforgeをインストールする
    - name: add repository
      yum: name={{item}}
      with_items:
        - http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
        - http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
        - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
        - http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm

    # 明示的に指定したいのでenabledは全て0にする
    - name: set repository epel,rpmforge,remi
      replace: dest=/etc/yum.repos.d/{{item}} regexp="enabled *= *1" replace="enabled=0"
      with_items:
        - epel.repo
        - rpmforge.repo
        - remi.repo
