---
- include: setup-RedHat.yml
#  when: ansible_os_family == 'RedHat'
#
#- include: setup-Debian.yml
#  when: ansible_os_family == 'Debian'

- name: Install forever (to run Node.js apps).
  npm: name=forever global=yes state=latest
  when: nodejs_forever

- name: Install additional defined npm global packages.
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('') }}"
    global: yes
    state: latest
  with_items:
    - name: node-dev
    - name: bower
    - name: grunt-cli
    - name: gm
    - name: canvas
    - name: flags
    - name: browserify
    - name: express
    - name: express-generator
    - name: pm2
    - name: q
    - name: request
    - name: tmp
    - name: easyimage
    - name: node-inspector
    - name: config
    - name: image-size
    - name: compression
    - name: object-hash
    - name: fabric

- name: Install Extra Packages
  sudo: yes
  yum: name={{ item }} state=latest enablerepo=epel
  with_items:
    - cairo
    - cairo-devel
    - cairomm-devel
    - libjpeg-turbo-devel
    - pango
    - pango-devel
    - pangomm
    - pangomm-devel
    - GraphicsMagick
    - GraphicsMagick-devel
#      #    - libcairo2-devel
#      #    - libjpeg8-devel
#      #    - libpango1.0-devel
#      #    - libgif-devel
#      #    - libvips-devel
#      #    - libgsf-1-devel
#      #    - build-essential
