---
- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev

- name: install rbenv
  git: repo=https://github.com/sstephenson/rbenv.git
       dest={{ vagrant_home }}/.rbenv
       version=master

- name: add rbenv path to bash_profile
  copy: src=rbenv.sh dest=/etc/profile.d/rbenv.sh
  # copy: content="export PATH=\"/home/vagrant/.rbenv/bin:$PATH\"\neval \"$(rbenv init -)\"" dest=/etc/profile.d/rbenv.sh

- name: install ruby_build
  git: repo=https://github.com/sstephenson/ruby-build.git
       dest={{ vagrant_home }}/.rbenv/plugins/ruby-build
       version=master

- name: install ruby {{ rbenv.version }}
  shell: "export RBENV_ROOT={{ vagrant_home }}/.rbenv; export PATH=$RBENV_ROOT/bin:$PATH; echo N | rbenv install {{ rbenv.version }}; rbenv global {{ rbenv.version }}"
  args:
    creates: "{{ vagrant_home }}/.rbenv/versions/{{ rbenv.version }}/"

- name: install bundler
  shell: "{{ vagrant_home }}/.rbenv/shims/gem install bundler"
  args:
    creates: "{{ vagrant_home }}/.rbenv/shims/bundle"

- name: change ~/.rbenv owner to vagrant
  file: path={{ vagrant_home }}/.rbenv state=directory owner=vagrant group=vagrant recurse=yes
