---
server:
    install: '1'
    packages: [vim, git, imagemagick, nodejs, npm, screen, tmux, rsync]
    timezone: Asia/Tokyo
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: myApp.vb, ip: 192.168.33.99, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /var/www
    servername: myApp.vb
mysql:
    install: '1'
    root_password: crea0201
    database: db
    user: mysql_user
    password: crea0201
    dump: ''
redis:
    install: '1'
    port: '6379'
php:
    install: '1'
    ppa: php5-5.6
# already include php5-mbstring ubuntu trusty64
#    packages: [php5-cli, php-pear, php5-curl, php5-imagick, php5-common, php5-fpm, php5-gd, php5-mbstring, php5-mcrypt, php5-memcache, php5-memcached, php5-mysql, php5-xdebug]
    packages: [php5-cli, php-pear, php5-curl, php5-imagick, php5-common, php5-fpm, php5-gd, php5-mcrypt, php5-memcache, php5-memcached, php5-mysql, php5-xdebug]
    peclpackages: [APC, memcache, memcached, ZendOpcache, mysql, PDO_MYSQL, redis, libevent, imagick]
xdebug:
    install: '1'
composer:
    install: '1'
blackfire:
    install: '1'
    server_id: daa58c7a-cf4a-46cb-a7eb-2b1434572e80
    server_token: 46024bce6caa625a28eee78a456c6576b7a4e6a643923e271e3648374ee6ae2c
github:
    oauth_token: 58e0aae5d78a6024868e25a3a091654b13c18db6
