---
server:
    install: '1'
    packages: [vim, git, imagemagick, nodejs, npm, screen, tmux, rsync]
    timezone: Asia/Tokyo
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: myApp.vb, ip: 192.168.33.99, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /var/www
    servername: myApp.vb
# this value is override other vars_files
nginx_do_not_cache: 0
mysql:
    install: '1'
    root_password: crea0201
    database: db
    user: mysql_user
    password: crea0201
    dump: ''
redis:
    install: '1'
    port: '6379'
php:
    install: '1'
    ppa: php5-5.6
# already include php5-mbstring ubuntu trusty64
#    packages: [php5-cli, php-pear, php5-curl, php5-imagick, php5-common, php5-fpm, php5-gd, php5-mbstring, php5-mcrypt, php5-memcache, php5-memcached, php5-mysql, php5-xdebug]
    packages: [php5-cli, php-pear, php5-curl, php5-imagick, php5-common, php5-fpm, php5-gd, php5-mcrypt, php5-memcache, php5-memcached, php5-mysql, php5-xdebug]
    peclpackages: [APC, memcache, memcached, ZendOpcache, mysql, PDO_MYSQL, redis, libevent, imagick]
xdebug:
    install: '1'
composer:
    install: '1'
blackfire:
    install: '1'
    server_id:
    server_token:
github:
    oauth_token:

work_dir: /etc/nginx/cer
openssl_dir: "{{ work_dir }}/meesiSSL"
openssl_cnf: "{{ work_dir }}/meesiSSL/openssl.cnf"
ca:
  default_md: sha256
  digest: sha256
  days: 3650
  subject: "/C=JP/ST=Tokyo/O=organization/CN=ECC Test CA"
  key: ca-private.key
  certificate: ca.pem
req:
  digest: sha256
  key: private.key
  csr: req.pem
usr:
  digest: sha256
  extendedKeyUsage:
    - serverAuth
    - clientAuth
  certificate: server.pem
