---
server:
    install: '1'
    packages: [vim, git, ImageMagick, ImageMagick-devel, screen, tmux, rsync, gcc, tar, make]
    zoneinfo: Japan
    timezone: Asia/Tokyo
    locale: ja_JP.UTF-8
    localedef: ja_JP ja_JP.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: centos65, hostname: myApp.vb, ip: 192.168.33.99, memory: '2048', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
nginx:
    install: '1'
    docroot: /var/www
    servername: myApp.vb
    servernameAdmin: myAdmin.vb
    servernameNode: myNode.vb
# this value is override other vars_files
nginx_do_not_cache: 0
mysql:
    install: '1'
    root_password: crea0201
    database: db
    user: mysql_user
    password: crea0201
    dump: ''
redis:
    install: '1'
    port: '6379'
php:
    install: '1'
    packages: [php-cli, php-devel, php-pear, php-curl, php-imagick, php-opcache, php-common, php-fpm, php-gd, php-mcrypt, php-memcache, php-memcached, php-mysql, php-xdebug, php-pdo, curl-devel, libmcrypt, php-mcrypt]
    #pecl_packages: [ZendOpcache, mysql, redis, libevent, imagick]
    pecl_packages: [redis]
xdebug:
    install: '1'
composer:
    install: '1'
blackfire:
    install: '1'
    server_id:
    server_token:
github:
    oauth_token: d451c7e86d00b84b6c506c27f1a4ef9f71205275

work_dir: /etc/nginx/cer
openssl_dir: "{{ work_dir }}/meeesiSSL"
openssl_cnf: "{{ work_dir }}/meeesiSSL/openssl.cnf"
ca:
  default_md: sha256
  digest: sha256
  days: 3650
  subject: "/C=JP/ST=Tokyo/O=organization/CN=ECC Test CA"
  key: ca-private.key
  certificate: ca.pem
req:
  digest: sha256
  key: private.key
  csr: req.pem
usr:
  digest: sha256
  extendedKeyUsage:
    - serverAuth
    - clientAuth
  certificate: server.pem

vagrant_home: "/home/vagrant"

rvm:
  url: https://get.rvm.io
  temp_installer_path: /tmp/rvm-installer.sh

  # the packages which need for download rvm
  required_packages:
    - curl
    - gnupg2

rvm_install_type: system
rvm_auto_update_rvm: true
rvm_default_ruby_version: ruby-2.2.2

#nodejs_compile: True   # install tools for compiling native addons from npm
## Node.js version; e.g., "4.0", "0.12", "0.12.7"
#nodejs_version: "4.0"

# Set the version of Node.js to install (e.g. "0.10", "0.12", "4.x", "5.x").
nodejs_version: "5.x"

# Install forever, which is useful for running Node.js apps.
nodejs_forever: false

# Define a list of global packages to be installed with NPM.
nodejs_npm_global_packages:
    - name: node-dev
    - name: bower
    - name: grunt-cli
    - name: gm
    - name: canvas
    - name: flags
    - name: browserify
    - name: express
    - name: express-generator
    - name: pm2
    - name: q
    - name: request
    - name: tmp
    - name: easyimage
    - name: node-inspector
    - name: config
    - name: image-size
    - name: fabric

#  # Install a specific version of a package.
#  - name: jslint
#    version: 0.9.3
#  # Install the latest stable release of a package.
  ##  - name: node-sass
