---
- name: Install php5
  sudo: yes
  yum: name=php state=latest enablerepo=remi,remi-php56

- name: Install php-fpm
  sudo: yes
  yum: name=php-fpm state=latest enablerepo=remi,remi-php56,epel

- name: configure fpm
  template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf mode=0644

- name: set autoload php-fpm
  command: chkconfig php-fpm on

- name: restart php-fpm
  service: name=php-fpm state=restarted

- name: Install PHP Packages
  sudo: yes
  yum: name={{ item }} state=latest enablerepo=remi,remi-php56,epel
  with_items: php.packages
  when: php.packages is defined

- include: configure.yml
- include: pecl.yml
