---
- command: rm -r {{ openssl_dir }} removes={{ openssl_dir }}
- command: mkdir -p {{ openssl_dir }}
- template: src=openssl.cnf.j2 dest={{ openssl_dir }}/openssl.cnf
  tags:
    - certificate
    - request
    - ca
- command: openssl ecparam -out {{ ca.key }} -name prime256v1 -genkey
           creates={{ ca.key }}
  tags:
    - certificate
    - ca
- command: >
    openssl req -config {{ openssl_cnf }}
                -new \
                -x509 \
                -key {{ ca.key }} \
                -{{ ca.digest }} \
                -days {{ ca.days }} \
                -subj "{{ ca.subject }}" \
                -extensions v3_ca \
                -out {{ ca.certificate }}
    creates={{ ca.certificate }}
  tags:
    - certificate
    - ca
- command: openssl ecparam -out {{ req.key }} -name prime256v1 -genkey
  tags:
    - certificate
    - request
- command: >
    openssl req -config {{ openssl_cnf }} \
                -new \
                -key {{ req.key }} \
                -{{ req.digest }} \
                -outform PEM \
                -keyform PEM \
                -out {{ req.csr }} \
                -subj "{{ ca.subject }}"
  tags:
    - certificate
    - request
- command: mkdir -p {{ openssl_dir }}/newcerts
  tags: certificate
- command: touch {{ openssl_dir }}/index.txt
           creates={{ openssl_dir }}/index.txt
  tags: certificate
- shell: echo 00 > {{ openssl_dir }}/serial
         creates={{ openssl_dir }}/serial
  tags: certificate
- command: >
    openssl ca -config {{ openssl_cnf }} \
               -in {{ req.csr }} \
               -keyfile {{ ca.key }} \
               -cert {{ ca.certificate }} \
               -extensions usr_cert \
               -batch \
               -out {{ usr.certificate }}
  tags: certificate
- command: mv {{ ca.certificate }} {{ ca.key }} {{ req.key }} {{ req.csr }} {{ usr.certificate }} {{ openssl_dir }}
