---
#- name: Add ppa Repository
#  sudo: yes
#  apt_repository: repo=ppa:chris-lea/node.js
#
#- name: Add ppa Repository
#  sudo: yes
#  apt_repository: repo=ppa:lovell/trusty-backport-vips

- name: Install Extra Packages
  sudo: yes
  yum: name={{ item }} state=latest enablerepo=epel
  with_items:
    - python
    - gcc-c++
    - make

- name: Download setup shell for nodejs
  shell: "curl -sL https://rpm.nodesource.com/setup_4.x | bash -"

- name: Install nodejs
  yum: name=nodejs state=latest

- name: Install Extra Packages
  sudo: yes
  yum: name={{ item }} state=latest enablerepo=epel
  with_items:
    - libcairo2-dev
    - libjpeg8-dev
    - libpango1.0-dev
    - libgif-dev
    - libvips-dev
    - libgsf-1-dev
    - build-essential

- name: Install Extra Packages
  sudo: yes
  yum: name=http://mirrors.ustc.edu.cn/fedora/epel/6/x86_64/GraphicsMagick-1.3.14-1.el6.x86_64.rpm state=present
