---
- name: github-auth limit 1
  shell: mkdir -p ~/.composer/
  ignore_errors: yes
- name: github-auth limit 2
  shell: chmod -R 777 ~/.composer/
  ignore_errors: yes
- name: github-auth limit 3
  template: src=auth.json.tpl dest=~/.composer/auth.json
  ignore_errors: yes
- name: install oil command
  shell: curl get.fuelphp.com/oil | sh
  ignore_errors: yes
- name: install FuelPHP
  git: repo=https://github.com/fuel/fuel dest={{ proj_sync_path }} version=1.7/master recursive=yes
  ignore_errors: yes
- name: setup1 FuelPHP
  shell: cd {{ proj_sync_path }}; php composer.phar self-update
  register: fuel_selfupdate
  ignore_errors: yes
- debug: msg="rc:{{fuel_selfupdate.rc}} stdout:{{fuel_selfupdate.stdout}} stderr:{{fuel_selfupdate.stderr}}"
- name: setup2 FuelPHP
  shell: cd {{ proj_sync_path }}; php composer.phar update
  register: fuel_update
  ignore_errors: yes
#- debug: msg="rc:{{fuel_update.rc}} stdout:{{fuel_update.stdout}} stderr:{{fuel_update.stderr}}"
- name: setup3 FuelPHP
  shell: cd {{ proj_sync_path }}; php oil refine install
- name: generate link docroot
  shell: cd {{ proj_sync_path }}; ln -s {{ proj_sync_path }} {{ proj_path }}
  ignore_errors: yes
