---
    - hosts: 192.168.33.99
      sudo: yes
      vars_files:
        - vars/all.yml
        - vars/development_local.yml
      roles:
        - common
        - server
        - vagrant_local
        - dev_tools
        # windowsでsmbを有効にするときはコメントアウトを外す
        #- samba
        - php
        - composer
        - mysql
        - redis
        - xdebug
        #- blackfire
        - self-ssl
        - web
        - webframework
