---
# file: webservers.yml
- hosts: localhost
  sudo: yes
  vars_files:
    - vars/all.yml
    - vars/{{ stage }}.yml
  roles:
    - common
    - server
    - vagrant_local
    # windowsでsmbを有効にするときはコメントアウトを外す
    #- samba
    - mysql
    - php
    - composer
    - rvm
    - nodejs_cent
    - dev_tools
    - selfssl
    - web
    - bashrc
