---
# file: webservers.yml
- hosts: localhost
  sudo: yes
  vars_files:
    - vars/all.yml
    - vars/{{ stage }}.yml
  roles:
    - app
    - common
    - server
    - vagrant_local
    # windowsでsmbを有効にするときはコメントアウトを外す
    #- samba
    - php
    - composer
    - rbenv
    - nodejs
    - dev_tools
    - redis
    - xdebug
    #- blackfire
    - selfssl
    - web
    - webframework
