---
- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - autoconf
    - automake
    - libtool
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm3
    - libgdbm-dev

- name: install signature rvm
  sudo: yes
  command: bash -c "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"

- name: install rvm
  command: bash -c "curl -L https://get.rvm.io | bash -s stable"

- name: reload rvm
  shell: "rvm install {{ rvm.version }}"

- name: set version:{{ rvm.version }} rvm
  shell: "rvm use {{ rvm.version }} --default"
